name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ 3.9 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: nbtermix-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install nbtermix
      run: |
        pip install -e .

    - name: Check style
      run: |
        black --check nbtermix
        flake8 --max-line-length 100 nbtermix

    - name: Run tests
      run: |
        mypy nbtermix
        nbtermix --help
        py.test nbtermix/tests
